import type { FrameworkSeedControl } from './types';

export const CIS_CSC_V81_FRAMEWORK_NAME = 'CIS Critical Security Controls v8.1';

export const CIS_CSC_V81_CONTROLS: FrameworkSeedControl[] = [
  { controlId: 'CIS-1.1', function: 'CIS Control 1', category: 'Inventory and Control of Enterprise Assets', title: 'Establish and Maintain Detailed Enterprise Asset Inventory' },
  { controlId: 'CIS-1.2', function: 'CIS Control 1', category: 'Inventory and Control of Enterprise Assets', title: 'Address Unauthorized Assets' },
  { controlId: 'CIS-1.3', function: 'CIS Control 1', category: 'Inventory and Control of Enterprise Assets', title: 'Utilize an Active Discovery Tool' },
  { controlId: 'CIS-1.4', function: 'CIS Control 1', category: 'Inventory and Control of Enterprise Assets', title: 'Use Dynamic Host Configuration Protocol (DHCP) Logging to Update Enterprise Asset Inventory' },
  { controlId: 'CIS-1.5', function: 'CIS Control 1', category: 'Inventory and Control of Enterprise Assets', title: 'Use a Passive Asset Discovery Tool' },
  { controlId: 'CIS-2.1', function: 'CIS Control 2', category: 'Inventory and Control of Software Assets', title: 'Establish and Maintain a Software Inventory' },
  { controlId: 'CIS-2.2', function: 'CIS Control 2', category: 'Inventory and Control of Software Assets', title: 'Ensure Authorized Software is Currently Supported' },
  { controlId: 'CIS-2.3', function: 'CIS Control 2', category: 'Inventory and Control of Software Assets', title: 'Address Unauthorized Software' },
  { controlId: 'CIS-2.4', function: 'CIS Control 2', category: 'Inventory and Control of Software Assets', title: 'Utilize Automated Software Inventory Tools' },
  { controlId: 'CIS-2.5', function: 'CIS Control 2', category: 'Inventory and Control of Software Assets', title: 'Allowlist Authorized Software' },
  { controlId: 'CIS-2.6', function: 'CIS Control 2', category: 'Inventory and Control of Software Assets', title: 'Allowlist Authorized Libraries' },
  { controlId: 'CIS-2.7', function: 'CIS Control 2', category: 'Inventory and Control of Software Assets', title: 'Allowlist Authorized Scripts' },
  { controlId: 'CIS-3.1', function: 'CIS Control 3', category: 'Data Protection', title: 'Establish and Maintain a Data Management Process' },
  { controlId: 'CIS-3.2', function: 'CIS Control 3', category: 'Data Protection', title: 'Establish and Maintain a Data Inventory' },
  { controlId: 'CIS-3.3', function: 'CIS Control 3', category: 'Data Protection', title: 'Configure Data Access Control Lists' },
  { controlId: 'CIS-3.4', function: 'CIS Control 3', category: 'Data Protection', title: 'Enforce Data Retention' },
  { controlId: 'CIS-3.5', function: 'CIS Control 3', category: 'Data Protection', title: 'Securely Dispose of Data' },
  { controlId: 'CIS-3.6', function: 'CIS Control 3', category: 'Data Protection', title: 'Encrypt Data on End-User Devices' },
  { controlId: 'CIS-3.7', function: 'CIS Control 3', category: 'Data Protection', title: 'Establish and Maintain a Data Classification Scheme' },
  { controlId: 'CIS-3.8', function: 'CIS Control 3', category: 'Data Protection', title: 'Document Data Flows' },
  { controlId: 'CIS-3.9', function: 'CIS Control 3', category: 'Data Protection', title: 'Encrypt Data on Removable Media' },
  { controlId: 'CIS-3.10', function: 'CIS Control 3', category: 'Data Protection', title: 'Encrypt Sensitive Data in Transit' },
  { controlId: 'CIS-3.11', function: 'CIS Control 3', category: 'Data Protection', title: 'Encrypt Sensitive Data at Rest' },
  { controlId: 'CIS-3.12', function: 'CIS Control 3', category: 'Data Protection', title: 'Segment Data Processing and Storage Based on Sensitivity' },
  { controlId: 'CIS-3.13', function: 'CIS Control 3', category: 'Data Protection', title: 'Deploy a Data Loss Prevention Solution' },
  { controlId: 'CIS-3.14', function: 'CIS Control 3', category: 'Data Protection', title: 'Log Sensitive Data Access' },
  { controlId: 'CIS-4.1', function: 'CIS Control 4', category: 'Secure Configuration of Enterprise Assets and Software', title: 'Establish and Maintain a Secure Configuration Process' },
  { controlId: 'CIS-4.2', function: 'CIS Control 4', category: 'Secure Configuration of Enterprise Assets and Software', title: 'Establish and Maintain a Secure Configuration Process for Network Infrastructure' },
  { controlId: 'CIS-4.3', function: 'CIS Control 4', category: 'Secure Configuration of Enterprise Assets and Software', title: 'Configure Automatic Session Locking on Enterprise Assets' },
  { controlId: 'CIS-4.4', function: 'CIS Control 4', category: 'Secure Configuration of Enterprise Assets and Software', title: 'Implement and Manage a Firewall on Servers' },
  { controlId: 'CIS-4.5', function: 'CIS Control 4', category: 'Secure Configuration of Enterprise Assets and Software', title: 'Implement and Manage a Firewall on End-User Devices' },
  { controlId: 'CIS-4.6', function: 'CIS Control 4', category: 'Secure Configuration of Enterprise Assets and Software', title: 'Securely Manage Enterprise Assets and Software' },
  { controlId: 'CIS-4.7', function: 'CIS Control 4', category: 'Secure Configuration of Enterprise Assets and Software', title: 'Manage Default Accounts on Enterprise Assets and Software' },
  { controlId: 'CIS-4.8', function: 'CIS Control 4', category: 'Secure Configuration of Enterprise Assets and Software', title: 'Uninstall or Disable Unnecessary Services on Enterprise Assets and Software' },
  { controlId: 'CIS-4.9', function: 'CIS Control 4', category: 'Secure Configuration of Enterprise Assets and Software', title: 'Configure Trusted DNS Servers on Enterprise Assets' },
  { controlId: 'CIS-4.10', function: 'CIS Control 4', category: 'Secure Configuration of Enterprise Assets and Software', title: 'Enforce Automatic Device Lockout on Portable End-User Devices' },
  { controlId: 'CIS-4.11', function: 'CIS Control 4', category: 'Secure Configuration of Enterprise Assets and Software', title: 'Enforce Remote Wipe Capability on Portable End-User Devices' },
  { controlId: 'CIS-4.12', function: 'CIS Control 4', category: 'Secure Configuration of Enterprise Assets and Software', title: 'Separate Enterprise Workspaces on Mobile End-User Devices' },
  { controlId: 'CIS-5.1', function: 'CIS Control 5', category: 'Account Management', title: 'Establish and Maintain an Inventory of Accounts' },
  { controlId: 'CIS-5.2', function: 'CIS Control 5', category: 'Account Management', title: 'Use Unique Passwords' },
  { controlId: 'CIS-5.3', function: 'CIS Control 5', category: 'Account Management', title: 'Disable Dormant Accounts' },
  { controlId: 'CIS-5.4', function: 'CIS Control 5', category: 'Account Management', title: 'Restrict Administrator Privileges to Dedicated Administrator Accounts' },
  { controlId: 'CIS-5.5', function: 'CIS Control 5', category: 'Account Management', title: 'Establish and Maintain an Inventory of Service Accounts' },
  { controlId: 'CIS-5.6', function: 'CIS Control 5', category: 'Account Management', title: 'Centralize Account Management' },
  { controlId: 'CIS-6.1', function: 'CIS Control 6', category: 'Access Control Management', title: 'Establish an Access Granting Process' },
  { controlId: 'CIS-6.2', function: 'CIS Control 6', category: 'Access Control Management', title: 'Establish an Access Revoking Process' },
  { controlId: 'CIS-6.3', function: 'CIS Control 6', category: 'Access Control Management', title: 'Require MFA for Externally-Exposed Applications' },
  { controlId: 'CIS-6.4', function: 'CIS Control 6', category: 'Access Control Management', title: 'Require MFA for Remote Network Access' },
  { controlId: 'CIS-6.5', function: 'CIS Control 6', category: 'Access Control Management', title: 'Require MFA for Administrative Access' },
  { controlId: 'CIS-6.6', function: 'CIS Control 6', category: 'Access Control Management', title: 'Establish and Maintain an Inventory of Authentication and Authorization Systems' },
  { controlId: 'CIS-6.7', function: 'CIS Control 6', category: 'Access Control Management', title: 'Centralize Access Control' },
  { controlId: 'CIS-6.8', function: 'CIS Control 6', category: 'Access Control Management', title: 'Define and Maintain Role-Based Access Control' },
  { controlId: 'CIS-7.1', function: 'CIS Control 7', category: 'Continuous Vulnerability Management', title: 'Establish and Maintain a Vulnerability Management Process' },
  { controlId: 'CIS-7.2', function: 'CIS Control 7', category: 'Continuous Vulnerability Management', title: 'Establish and Maintain a Remediation Process' },
  { controlId: 'CIS-7.3', function: 'CIS Control 7', category: 'Continuous Vulnerability Management', title: 'Perform Automated Operating System Patch Management' },
  { controlId: 'CIS-7.4', function: 'CIS Control 7', category: 'Continuous Vulnerability Management', title: 'Perform Automated Application Patch Management' },
  { controlId: 'CIS-7.5', function: 'CIS Control 7', category: 'Continuous Vulnerability Management', title: 'Perform Automated Vulnerability Scans of Internal Enterprise Assets' },
  { controlId: 'CIS-7.6', function: 'CIS Control 7', category: 'Continuous Vulnerability Management', title: 'Perform Automated Vulnerability Scans of Externally-Exposed Enterprise Assets' },
  { controlId: 'CIS-7.7', function: 'CIS Control 7', category: 'Continuous Vulnerability Management', title: 'Remediate Detected Vulnerabilities' },
  { controlId: 'CIS-8.1', function: 'CIS Control 8', category: 'Audit Log Management', title: 'Establish and Maintain an Audit Log Management Process' },
  { controlId: 'CIS-8.2', function: 'CIS Control 8', category: 'Audit Log Management', title: 'Collect Audit Logs' },
  { controlId: 'CIS-8.3', function: 'CIS Control 8', category: 'Audit Log Management', title: 'Ensure Adequate Audit Log Storage' },
  { controlId: 'CIS-8.4', function: 'CIS Control 8', category: 'Audit Log Management', title: 'Standardize Time Synchronization' },
  { controlId: 'CIS-8.5', function: 'CIS Control 8', category: 'Audit Log Management', title: 'Collect Detailed Audit Logs' },
  { controlId: 'CIS-8.6', function: 'CIS Control 8', category: 'Audit Log Management', title: 'Collect DNS Query Audit Logs' },
  { controlId: 'CIS-8.7', function: 'CIS Control 8', category: 'Audit Log Management', title: 'Collect URL Request Audit Logs' },
  { controlId: 'CIS-8.8', function: 'CIS Control 8', category: 'Audit Log Management', title: 'Collect Command-Line Audit Logs' },
  { controlId: 'CIS-8.9', function: 'CIS Control 8', category: 'Audit Log Management', title: 'Centralize Audit Logs' },
  { controlId: 'CIS-8.10', function: 'CIS Control 8', category: 'Audit Log Management', title: 'Retain Audit Logs' },
  { controlId: 'CIS-8.11', function: 'CIS Control 8', category: 'Audit Log Management', title: 'Conduct Audit Log Reviews' },
  { controlId: 'CIS-8.12', function: 'CIS Control 8', category: 'Audit Log Management', title: 'Collect Service Provider Logs' },
  { controlId: 'CIS-9.1', function: 'CIS Control 9', category: 'Email and Web Browser Protections', title: 'Ensure Use of Only Fully Supported Browsers and Email Clients' },
  { controlId: 'CIS-9.2', function: 'CIS Control 9', category: 'Email and Web Browser Protections', title: 'Use DNS Filtering Services' },
  { controlId: 'CIS-9.3', function: 'CIS Control 9', category: 'Email and Web Browser Protections', title: 'Maintain and Enforce Network-Based URL Filters' },
  { controlId: 'CIS-9.4', function: 'CIS Control 9', category: 'Email and Web Browser Protections', title: 'Restrict Unnecessary or Unauthorized Browser and Email Client Extensions' },
  { controlId: 'CIS-9.5', function: 'CIS Control 9', category: 'Email and Web Browser Protections', title: 'Implement DMARC' },
  { controlId: 'CIS-9.6', function: 'CIS Control 9', category: 'Email and Web Browser Protections', title: 'Block Unnecessary File Types' },
  { controlId: 'CIS-9.7', function: 'CIS Control 9', category: 'Email and Web Browser Protections', title: 'Deploy and Maintain Email Server Anti-Malware Protections' },
  { controlId: 'CIS-10.1', function: 'CIS Control 10', category: 'Malware Defenses', title: 'Deploy and Maintain Anti-Malware Software' },
  { controlId: 'CIS-10.2', function: 'CIS Control 10', category: 'Malware Defenses', title: 'Configure Automatic Anti-Malware Signature Updates' },
  { controlId: 'CIS-10.3', function: 'CIS Control 10', category: 'Malware Defenses', title: 'Disable Autorun and Autoplay for Removable Media' },
  { controlId: 'CIS-10.4', function: 'CIS Control 10', category: 'Malware Defenses', title: 'Configure Automatic Anti-Malware Scanning of Removable Media' },
  { controlId: 'CIS-10.5', function: 'CIS Control 10', category: 'Malware Defenses', title: 'Enable Anti-Exploitation Features' },
  { controlId: 'CIS-10.6', function: 'CIS Control 10', category: 'Malware Defenses', title: 'Centrally Manage Anti-Malware Software' },
  { controlId: 'CIS-10.7', function: 'CIS Control 10', category: 'Malware Defenses', title: 'Use Behavior-Based Anti-Malware Software' },
  { controlId: 'CIS-11.1', function: 'CIS Control 11', category: 'Data Recovery', title: 'Establish and Maintain a Data Recovery Process' },
  { controlId: 'CIS-11.2', function: 'CIS Control 11', category: 'Data Recovery', title: 'Perform Automated Backups' },
  { controlId: 'CIS-11.3', function: 'CIS Control 11', category: 'Data Recovery', title: 'Protect Recovery Data' },
  { controlId: 'CIS-11.4', function: 'CIS Control 11', category: 'Data Recovery', title: 'Establish and Maintain an Isolated Instance of Recovery Data' },
  { controlId: 'CIS-11.5', function: 'CIS Control 11', category: 'Data Recovery', title: 'Test Data Recovery' },
  { controlId: 'CIS-12.1', function: 'CIS Control 12', category: 'Network Infrastructure Management', title: 'Ensure Network Infrastructure is Up-to-Date' },
  { controlId: 'CIS-12.2', function: 'CIS Control 12', category: 'Network Infrastructure Management', title: 'Establish and Maintain a Secure Network Architecture' },
  { controlId: 'CIS-12.3', function: 'CIS Control 12', category: 'Network Infrastructure Management', title: 'Securely Manage Network Infrastructure' },
  { controlId: 'CIS-12.4', function: 'CIS Control 12', category: 'Network Infrastructure Management', title: 'Establish and Maintain Architecture Diagram(s)' },
  { controlId: 'CIS-12.5', function: 'CIS Control 12', category: 'Network Infrastructure Management', title: 'Centralize Network Authentication, Authorization, and Auditing (AAA)' },
  { controlId: 'CIS-12.6', function: 'CIS Control 12', category: 'Network Infrastructure Management', title: 'Use of Secure Network Management and Communication Protocols' },
  { controlId: 'CIS-12.7', function: 'CIS Control 12', category: 'Network Infrastructure Management', title: "Ensure Remote Devices Utilize a VPN and are Connecting to an Enterprise's AAA Infrastructure" },
  { controlId: 'CIS-12.8', function: 'CIS Control 12', category: 'Network Infrastructure Management', title: 'Establish and Maintain Dedicated Computing Resources for All Administrative Work' },
  { controlId: 'CIS-13.1', function: 'CIS Control 13', category: 'Network Monitoring and Defense', title: 'Centralize Security Event Alerting' },
  { controlId: 'CIS-13.2', function: 'CIS Control 13', category: 'Network Monitoring and Defense', title: 'Deploy a Host-Based Intrusion Detection Solution' },
  { controlId: 'CIS-13.3', function: 'CIS Control 13', category: 'Network Monitoring and Defense', title: 'Deploy a Network Intrusion Detection Solution' },
  { controlId: 'CIS-13.4', function: 'CIS Control 13', category: 'Network Monitoring and Defense', title: 'Perform Traffic Filtering Between Network Segments' },
  { controlId: 'CIS-13.5', function: 'CIS Control 13', category: 'Network Monitoring and Defense', title: 'Manage Access Control for Remote Assets' },
  { controlId: 'CIS-13.6', function: 'CIS Control 13', category: 'Network Monitoring and Defense', title: 'Collect Network Traffic Flow Logs' },
  { controlId: 'CIS-13.7', function: 'CIS Control 13', category: 'Network Monitoring and Defense', title: 'Deploy a Host-Based Intrusion Prevention Solution' },
  { controlId: 'CIS-13.8', function: 'CIS Control 13', category: 'Network Monitoring and Defense', title: 'Deploy a Network Intrusion Prevention Solution' },
  { controlId: 'CIS-13.9', function: 'CIS Control 13', category: 'Network Monitoring and Defense', title: 'Deploy Port-Level Access Control' },
  { controlId: 'CIS-13.10', function: 'CIS Control 13', category: 'Network Monitoring and Defense', title: 'Perform Application Layer Filtering' },
  { controlId: 'CIS-13.11', function: 'CIS Control 13', category: 'Network Monitoring and Defense', title: 'Tune Security Event Alerting Thresholds' },
  { controlId: 'CIS-14.1', function: 'CIS Control 14', category: 'Security Awareness and Skills Training', title: 'Establish and Maintain a Security Awareness Program' },
  { controlId: 'CIS-14.2', function: 'CIS Control 14', category: 'Security Awareness and Skills Training', title: 'Train Workforce Members to Recognize Social Engineering Attacks' },
  { controlId: 'CIS-14.3', function: 'CIS Control 14', category: 'Security Awareness and Skills Training', title: 'Train Workforce Members on Authentication Best Practices' },
  { controlId: 'CIS-14.4', function: 'CIS Control 14', category: 'Security Awareness and Skills Training', title: 'Train Workforce Members on Data Handling Best Practices' },
  { controlId: 'CIS-14.5', function: 'CIS Control 14', category: 'Security Awareness and Skills Training', title: 'Train Workforce Members on Causes of Unintentional Data Exposure' },
  { controlId: 'CIS-14.6', function: 'CIS Control 14', category: 'Security Awareness and Skills Training', title: 'Train Workforce Members on Recognizing and Reporting Security Incidents' },
  { controlId: 'CIS-14.7', function: 'CIS Control 14', category: 'Security Awareness and Skills Training', title: 'Train Workforce on How to Identify and Report if Their Enterprise Assets are Missing Security Updates' },
  { controlId: 'CIS-14.8', function: 'CIS Control 14', category: 'Security Awareness and Skills Training', title: 'Train Workforce on the Dangers of Connecting to and Transmitting Enterprise Data Over Insecure Networks' },
  { controlId: 'CIS-14.9', function: 'CIS Control 14', category: 'Security Awareness and Skills Training', title: 'Conduct Role-Specific Security Awareness and Skills Training' },
  { controlId: 'CIS-15.1', function: 'CIS Control 15', category: 'Service Provider Management', title: 'Establish and Maintain an Inventory of Service Providers' },
  { controlId: 'CIS-15.2', function: 'CIS Control 15', category: 'Service Provider Management', title: 'Establish and Maintain a Service Provider Management Policy' },
  { controlId: 'CIS-15.3', function: 'CIS Control 15', category: 'Service Provider Management', title: 'Classify Service Providers' },
  { controlId: 'CIS-15.4', function: 'CIS Control 15', category: 'Service Provider Management', title: 'Ensure Service Provider Contracts Include Security Requirements' },
  { controlId: 'CIS-15.5', function: 'CIS Control 15', category: 'Service Provider Management', title: 'Assess Service Providers' },
  { controlId: 'CIS-15.6', function: 'CIS Control 15', category: 'Service Provider Management', title: 'Monitor Service Providers' },
  { controlId: 'CIS-15.7', function: 'CIS Control 15', category: 'Service Provider Management', title: 'Securely Decommission Service Providers' },
  { controlId: 'CIS-16.1', function: 'CIS Control 16', category: 'Application Software Security', title: 'Establish and Maintain a Secure Application Development Process' },
  { controlId: 'CIS-16.2', function: 'CIS Control 16', category: 'Application Software Security', title: 'Establish and Maintain a Process to Accept and Address Software Vulnerabilities' },
  { controlId: 'CIS-16.3', function: 'CIS Control 16', category: 'Application Software Security', title: 'Perform Root Cause Analysis on Security Vulnerabilities' },
  { controlId: 'CIS-16.4', function: 'CIS Control 16', category: 'Application Software Security', title: 'Establish and Manage an Inventory of Third-Party Software Components' },
  { controlId: 'CIS-16.5', function: 'CIS Control 16', category: 'Application Software Security', title: 'Use Up-to-Date and Trusted Third-Party Software Components' },
  { controlId: 'CIS-16.6', function: 'CIS Control 16', category: 'Application Software Security', title: 'Establish and Maintain a Severity Rating System and Process for Application Vulnerabilities' },
  { controlId: 'CIS-16.7', function: 'CIS Control 16', category: 'Application Software Security', title: 'Use Standard Hardening Configuration Templates for Application Infrastructure' },
  { controlId: 'CIS-16.8', function: 'CIS Control 16', category: 'Application Software Security', title: 'Separate Production and Non-Production Systems' },
  { controlId: 'CIS-16.9', function: 'CIS Control 16', category: 'Application Software Security', title: 'Train Developers in Application Security Concepts and Secure Coding' },
  { controlId: 'CIS-16.10', function: 'CIS Control 16', category: 'Application Software Security', title: 'Apply Secure Design Principles in Application Architectures' },
  { controlId: 'CIS-16.11', function: 'CIS Control 16', category: 'Application Software Security', title: 'Leverage Vetted Modules or Services for Application Security Components' },
  { controlId: 'CIS-16.12', function: 'CIS Control 16', category: 'Application Software Security', title: 'Implement Code-Level Security Checks' },
  { controlId: 'CIS-16.13', function: 'CIS Control 16', category: 'Application Software Security', title: 'Conduct Application Penetration Testing' },
  { controlId: 'CIS-16.14', function: 'CIS Control 16', category: 'Application Software Security', title: 'Conduct Threat Modeling' },
  { controlId: 'CIS-17.1', function: 'CIS Control 17', category: 'Incident Response Management', title: 'Designate Personnel to Manage Incident Handling' },
  { controlId: 'CIS-17.2', function: 'CIS Control 17', category: 'Incident Response Management', title: 'Establish and Maintain Contact Information for Reporting Security Incidents' },
  { controlId: 'CIS-17.3', function: 'CIS Control 17', category: 'Incident Response Management', title: 'Establish and Maintain an Enterprise Process for Reporting Incidents' },
  { controlId: 'CIS-17.4', function: 'CIS Control 17', category: 'Incident Response Management', title: 'Establish and Maintain an Incident Response Process' },
  { controlId: 'CIS-17.5', function: 'CIS Control 17', category: 'Incident Response Management', title: 'Assign Key Roles and Responsibilities' },
  { controlId: 'CIS-17.6', function: 'CIS Control 17', category: 'Incident Response Management', title: 'Define Mechanisms for Communicating During Incident Response' },
  { controlId: 'CIS-17.7', function: 'CIS Control 17', category: 'Incident Response Management', title: 'Conduct Routine Incident Response Exercises' },
  { controlId: 'CIS-17.8', function: 'CIS Control 17', category: 'Incident Response Management', title: 'Conduct Post-Incident Reviews' },
  { controlId: 'CIS-17.9', function: 'CIS Control 17', category: 'Incident Response Management', title: 'Establish and Maintain Security Incident Thresholds' },
  { controlId: 'CIS-18.1', function: 'CIS Control 18', category: 'Penetration Testing', title: 'Establish and Maintain a Penetration Testing Program' },
  { controlId: 'CIS-18.2', function: 'CIS Control 18', category: 'Penetration Testing', title: 'Perform Periodic External Penetration Tests' },
  { controlId: 'CIS-18.3', function: 'CIS Control 18', category: 'Penetration Testing', title: 'Remediate Penetration Test Findings' },
  { controlId: 'CIS-18.4', function: 'CIS Control 18', category: 'Penetration Testing', title: 'Validate Security Measures' },
  { controlId: 'CIS-18.5', function: 'CIS Control 18', category: 'Penetration Testing', title: 'Perform Periodic Internal Penetration Tests' },
];
