import type { FrameworkSeedControl } from './types';

export const NIST_CSF_20_FRAMEWORK_NAME = 'NIST CSF 2.0';

export const NIST_CSF_20_CONTROLS: FrameworkSeedControl[] = [
  { controlId: 'GV.OC-01', function: 'Govern', category: 'Organizational Context', title: 'Align cybersecurity risk management with the organizational mission' },
  { controlId: 'GV.OC-02', function: 'Govern', category: 'Organizational Context', title: 'Understand stakeholder needs and expectations for cybersecurity risk management' },
  { controlId: 'GV.OC-03', function: 'Govern', category: 'Organizational Context', title: 'Manage cybersecurity legal, regulatory, contractual, privacy, and civil liberties obligations' },
  { controlId: 'GV.OC-04', function: 'Govern', category: 'Organizational Context', title: 'Understand and communicate externally expected critical objectives, capabilities, and services' },
  { controlId: 'GV.OC-05', function: 'Govern', category: 'Organizational Context', title: 'Understand and communicate dependencies on outcomes, capabilities, and services' },
  { controlId: 'GV.RM-01', function: 'Govern', category: 'Risk Management Strategy', title: 'Establish and agree cybersecurity risk management objectives' },
  { controlId: 'GV.RM-02', function: 'Govern', category: 'Risk Management Strategy', title: 'Establish, communicate, and maintain risk appetite and risk tolerance' },
  { controlId: 'GV.RM-03', function: 'Govern', category: 'Risk Management Strategy', title: 'Include cybersecurity risk activities and outcomes in enterprise risk management' },
  { controlId: 'GV.RM-04', function: 'Govern', category: 'Risk Management Strategy', title: 'Establish and communicate strategic direction for risk response options' },
  { controlId: 'GV.RM-05', function: 'Govern', category: 'Risk Management Strategy', title: 'Establish communication channels for cybersecurity and third-party risks' },
  { controlId: 'GV.RM-06', function: 'Govern', category: 'Risk Management Strategy', title: 'Use a standardized method to calculate, document, categorize, and prioritize cybersecurity risks' },
  { controlId: 'GV.RM-07', function: 'Govern', category: 'Risk Management Strategy', title: 'Identify positive strategic opportunities in cybersecurity risk discussions' },
  { controlId: 'GV.RR-01', function: 'Govern', category: 'Roles, Responsibilities, and Authorities', title: 'Hold leadership accountable for cybersecurity risk and a risk-aware culture' },
  { controlId: 'GV.RR-02', function: 'Govern', category: 'Roles, Responsibilities, and Authorities', title: 'Establish, communicate, understand, and enforce cybersecurity roles and authorities' },
  { controlId: 'GV.RR-03', function: 'Govern', category: 'Roles, Responsibilities, and Authorities', title: 'Allocate resources consistent with the cybersecurity risk strategy and responsibilities' },
  { controlId: 'GV.RR-04', function: 'Govern', category: 'Roles, Responsibilities, and Authorities', title: 'Include cybersecurity considerations in human resources practices' },
  { controlId: 'GV.PO-01', function: 'Govern', category: 'Policy', title: 'Establish, communicate, and enforce cybersecurity risk policy based on context and priorities' },
  { controlId: 'GV.PO-02', function: 'Govern', category: 'Policy', title: 'Review and update cybersecurity risk policy as requirements, threats, technology, and mission change' },
  { controlId: 'GV.OV-01', function: 'Govern', category: 'Oversight', title: 'Review cybersecurity risk strategy outcomes to inform strategic direction' },
  { controlId: 'GV.OV-02', function: 'Govern', category: 'Oversight', title: 'Review and adjust cybersecurity risk strategy against requirements and risks' },
  { controlId: 'GV.OV-03', function: 'Govern', category: 'Oversight', title: 'Evaluate cybersecurity risk management performance and adjust as needed' },
  { controlId: 'GV.SC-01', function: 'Govern', category: 'Cybersecurity Supply Chain Risk Management', title: 'Establish and agree supply chain risk program, strategy, objectives, policies, and processes' },
  { controlId: 'GV.SC-02', function: 'Govern', category: 'Cybersecurity Supply Chain Risk Management', title: 'Coordinate cybersecurity supply chain roles and responsibilities internally and externally' },
  { controlId: 'GV.SC-03', function: 'Govern', category: 'Cybersecurity Supply Chain Risk Management', title: 'Integrate supply chain risk management into cyber and enterprise risk processes' },
  { controlId: 'GV.SC-04', function: 'Govern', category: 'Cybersecurity Supply Chain Risk Management', title: 'Identify suppliers and prioritize them by criticality' },
  { controlId: 'GV.SC-05', function: 'Govern', category: 'Cybersecurity Supply Chain Risk Management', title: 'Include supply chain cybersecurity requirements in contracts and agreements' },
  { controlId: 'GV.SC-06', function: 'Govern', category: 'Cybersecurity Supply Chain Risk Management', title: 'Perform planning and due diligence before supplier or third-party relationships' },
  { controlId: 'GV.SC-07', function: 'Govern', category: 'Cybersecurity Supply Chain Risk Management', title: 'Assess, record, prioritize, respond to, and monitor supplier and third-party risks' },
  { controlId: 'GV.SC-08', function: 'Govern', category: 'Cybersecurity Supply Chain Risk Management', title: 'Include relevant suppliers and third parties in incident planning, response, and recovery' },
  { controlId: 'GV.SC-09', function: 'Govern', category: 'Cybersecurity Supply Chain Risk Management', title: 'Monitor supply chain security practices across the technology product and service life cycle' },
  { controlId: 'GV.SC-10', function: 'Govern', category: 'Cybersecurity Supply Chain Risk Management', title: 'Plan for supply chain risk activities after partnerships or services end' },
  { controlId: 'ID.AM-01', function: 'Identify', category: 'Asset Management', title: 'Maintain inventories of organization-managed hardware' },
  { controlId: 'ID.AM-02', function: 'Identify', category: 'Asset Management', title: 'Maintain inventories of organization-managed software, services, and systems' },
  { controlId: 'ID.AM-03', function: 'Identify', category: 'Asset Management', title: 'Maintain representations of authorized network communications and data flows' },
  { controlId: 'ID.AM-04', function: 'Identify', category: 'Asset Management', title: 'Maintain inventories of supplier-provided services' },
  { controlId: 'ID.AM-05', function: 'Identify', category: 'Asset Management', title: 'Prioritize assets by classification, criticality, resources, and mission impact' },
  { controlId: 'ID.AM-07', function: 'Identify', category: 'Asset Management', title: 'Maintain inventories of designated data types and related metadata' },
  { controlId: 'ID.AM-08', function: 'Identify', category: 'Asset Management', title: 'Manage systems, hardware, software, services, and data through their life cycles' },
  { controlId: 'ID.RA-01', function: 'Identify', category: 'Risk Assessment', title: 'Identify, validate, and record asset vulnerabilities' },
  { controlId: 'ID.RA-02', function: 'Identify', category: 'Risk Assessment', title: 'Receive cyber threat intelligence from sharing forums and sources' },
  { controlId: 'ID.RA-03', function: 'Identify', category: 'Risk Assessment', title: 'Identify and record internal and external threats' },
  { controlId: 'ID.RA-04', function: 'Identify', category: 'Risk Assessment', title: 'Identify and record likelihoods and impacts of threats exploiting vulnerabilities' },
  { controlId: 'ID.RA-05', function: 'Identify', category: 'Risk Assessment', title: 'Use threats, vulnerabilities, likelihoods, and impacts to understand and prioritize inherent risk' },
  { controlId: 'ID.RA-06', function: 'Identify', category: 'Risk Assessment', title: 'Choose, prioritize, plan, track, and communicate risk responses' },
  { controlId: 'ID.RA-07', function: 'Identify', category: 'Risk Assessment', title: 'Manage changes and exceptions and assess, record, and track risk impact' },
  { controlId: 'ID.RA-08', function: 'Identify', category: 'Risk Assessment', title: 'Establish vulnerability disclosure intake, analysis, and response processes' },
  { controlId: 'ID.RA-09', function: 'Identify', category: 'Risk Assessment', title: 'Assess hardware and software authenticity and integrity before acquisition and use' },
  { controlId: 'ID.RA-10', function: 'Identify', category: 'Risk Assessment', title: 'Assess critical suppliers before acquisition' },
  { controlId: 'ID.IM-01', function: 'Identify', category: 'Improvement', title: 'Identify improvements from evaluations' },
  { controlId: 'ID.IM-02', function: 'Identify', category: 'Improvement', title: 'Identify improvements from security testing and exercises with suppliers and third parties when relevant' },
  { controlId: 'ID.IM-03', function: 'Identify', category: 'Improvement', title: 'Identify improvements from operational process, procedure, and activity execution' },
  { controlId: 'ID.IM-04', function: 'Identify', category: 'Improvement', title: 'Establish, communicate, maintain, and improve incident response and cybersecurity operations plans' },
  { controlId: 'PR.AA-01', function: 'Protect', category: 'Identity Management, Authentication, and Access Control', title: 'Manage identities and credentials for authorized users, services, and hardware' },
  { controlId: 'PR.AA-02', function: 'Protect', category: 'Identity Management, Authentication, and Access Control', title: 'Proof identities and bind them to credentials based on interaction context' },
  { controlId: 'PR.AA-03', function: 'Protect', category: 'Identity Management, Authentication, and Access Control', title: 'Authenticate users, services, and hardware' },
  { controlId: 'PR.AA-04', function: 'Protect', category: 'Identity Management, Authentication, and Access Control', title: 'Protect, convey, and verify identity assertions' },
  { controlId: 'PR.AA-05', function: 'Protect', category: 'Identity Management, Authentication, and Access Control', title: 'Define, manage, enforce, and review access permissions using least privilege and separation of duties' },
  { controlId: 'PR.AA-06', function: 'Protect', category: 'Identity Management, Authentication, and Access Control', title: 'Manage, monitor, and enforce physical access to assets based on risk' },
  { controlId: 'PR.AT-01', function: 'Protect', category: 'Awareness and Training', title: 'Provide workforce awareness and training for general cybersecurity-risk-aware tasks' },
  { controlId: 'PR.AT-02', function: 'Protect', category: 'Awareness and Training', title: 'Provide specialized role training for relevant cybersecurity-risk-aware tasks' },
  { controlId: 'PR.DS-01', function: 'Protect', category: 'Data Security', title: 'Protect confidentiality, integrity, and availability of data at rest' },
  { controlId: 'PR.DS-02', function: 'Protect', category: 'Data Security', title: 'Protect confidentiality, integrity, and availability of data in transit' },
  { controlId: 'PR.DS-10', function: 'Protect', category: 'Data Security', title: 'Protect confidentiality, integrity, and availability of data in use' },
  { controlId: 'PR.DS-11', function: 'Protect', category: 'Data Security', title: 'Create, protect, maintain, and test data backups' },
  { controlId: 'PR.PS-01', function: 'Protect', category: 'Platform Security', title: 'Establish and apply configuration management practices' },
  { controlId: 'PR.PS-02', function: 'Protect', category: 'Platform Security', title: 'Maintain, replace, and remove software based on risk' },
  { controlId: 'PR.PS-03', function: 'Protect', category: 'Platform Security', title: 'Maintain, replace, and remove hardware based on risk' },
  { controlId: 'PR.PS-04', function: 'Protect', category: 'Platform Security', title: 'Generate log records and make them available for monitoring' },
  { controlId: 'PR.PS-05', function: 'Protect', category: 'Platform Security', title: 'Prevent installation and execution of unauthorized software' },
  { controlId: 'PR.PS-06', function: 'Protect', category: 'Platform Security', title: 'Integrate and monitor secure software development practices through the SDLC' },
  { controlId: 'PR.IR-01', function: 'Protect', category: 'Technology Infrastructure Resilience', title: 'Protect networks and environments from unauthorized logical access and use' },
  { controlId: 'PR.IR-02', function: 'Protect', category: 'Technology Infrastructure Resilience', title: 'Protect technology assets from environmental threats' },
  { controlId: 'PR.IR-03', function: 'Protect', category: 'Technology Infrastructure Resilience', title: 'Implement mechanisms to meet resilience requirements under normal and adverse conditions' },
  { controlId: 'PR.IR-04', function: 'Protect', category: 'Technology Infrastructure Resilience', title: 'Maintain adequate resource capacity to support availability' },
  { controlId: 'DE.CM-01', function: 'Detect', category: 'Continuous Monitoring', title: 'Monitor networks and network services for potentially adverse events' },
  { controlId: 'DE.CM-02', function: 'Detect', category: 'Continuous Monitoring', title: 'Monitor the physical environment for potentially adverse events' },
  { controlId: 'DE.CM-03', function: 'Detect', category: 'Continuous Monitoring', title: 'Monitor personnel activity and technology use for potentially adverse events' },
  { controlId: 'DE.CM-06', function: 'Detect', category: 'Continuous Monitoring', title: 'Monitor external service provider activities and services for potentially adverse events' },
  { controlId: 'DE.CM-09', function: 'Detect', category: 'Continuous Monitoring', title: 'Monitor computing hardware, software, runtime environments, and data for potentially adverse events' },
  { controlId: 'DE.AE-02', function: 'Detect', category: 'Adverse Event Analysis', title: 'Analyze potentially adverse events to understand associated activities' },
  { controlId: 'DE.AE-03', function: 'Detect', category: 'Adverse Event Analysis', title: 'Correlate information from multiple sources' },
  { controlId: 'DE.AE-04', function: 'Detect', category: 'Adverse Event Analysis', title: 'Understand the estimated impact and scope of adverse events' },
  { controlId: 'DE.AE-06', function: 'Detect', category: 'Adverse Event Analysis', title: 'Provide adverse event information to authorized staff and tools' },
  { controlId: 'DE.AE-07', function: 'Detect', category: 'Adverse Event Analysis', title: 'Integrate cyber threat intelligence and context into analysis' },
  { controlId: 'DE.AE-08', function: 'Detect', category: 'Adverse Event Analysis', title: 'Declare incidents when adverse events meet defined criteria' },
  { controlId: 'RS.MA-01', function: 'Respond', category: 'Incident Management', title: 'Execute the incident response plan with relevant third parties after incident declaration' },
  { controlId: 'RS.MA-02', function: 'Respond', category: 'Incident Management', title: 'Triage and validate incident reports' },
  { controlId: 'RS.MA-03', function: 'Respond', category: 'Incident Management', title: 'Categorize and prioritize incidents' },
  { controlId: 'RS.MA-04', function: 'Respond', category: 'Incident Management', title: 'Escalate or elevate incidents as needed' },
  { controlId: 'RS.MA-05', function: 'Respond', category: 'Incident Management', title: 'Apply criteria for initiating incident recovery' },
  { controlId: 'RS.AN-03', function: 'Respond', category: 'Incident Analysis', title: 'Analyze what occurred during an incident and determine root cause' },
  { controlId: 'RS.AN-06', function: 'Respond', category: 'Incident Analysis', title: 'Record investigation actions and preserve record integrity and provenance' },
  { controlId: 'RS.AN-07', function: 'Respond', category: 'Incident Analysis', title: 'Collect incident data and metadata and preserve integrity and provenance' },
  { controlId: 'RS.AN-08', function: 'Respond', category: 'Incident Analysis', title: 'Estimate and validate incident magnitude' },
  { controlId: 'RS.CO-02', function: 'Respond', category: 'Incident Response Reporting and Communication', title: 'Notify internal and external stakeholders of incidents' },
  { controlId: 'RS.CO-03', function: 'Respond', category: 'Incident Response Reporting and Communication', title: 'Share information with designated internal and external stakeholders' },
  { controlId: 'RS.MI-01', function: 'Respond', category: 'Incident Mitigation', title: 'Contain incidents' },
  { controlId: 'RS.MI-02', function: 'Respond', category: 'Incident Mitigation', title: 'Eradicate incidents' },
  { controlId: 'RC.RP-01', function: 'Recover', category: 'Incident Recovery Plan Execution', title: 'Execute the recovery portion of the incident response plan after initiation' },
  { controlId: 'RC.RP-02', function: 'Recover', category: 'Incident Recovery Plan Execution', title: 'Select, scope, prioritize, and perform recovery actions' },
  { controlId: 'RC.RP-03', function: 'Recover', category: 'Incident Recovery Plan Execution', title: 'Verify backup and restoration asset integrity before restoration' },
  { controlId: 'RC.RP-04', function: 'Recover', category: 'Incident Recovery Plan Execution', title: 'Consider critical mission functions and cyber risk management when establishing post-incident norms' },
  { controlId: 'RC.RP-05', function: 'Recover', category: 'Incident Recovery Plan Execution', title: 'Verify restored asset integrity and confirm normal operating status' },
  { controlId: 'RC.RP-06', function: 'Recover', category: 'Incident Recovery Plan Execution', title: 'Declare incident recovery complete and finalize incident documentation' },
  { controlId: 'RC.CO-03', function: 'Recover', category: 'Incident Recovery Communication', title: 'Communicate recovery activities and restoration progress to designated stakeholders' },
  { controlId: 'RC.CO-04', function: 'Recover', category: 'Incident Recovery Communication', title: 'Share public recovery updates through approved methods and messaging' },
];
